---
title: "Women & Power, Mary Beard"
---

[Back](https://CruzAdl.github.io/bookreviews.qmd) | [Home](https://CruzAdl.github.io/index.qmd)

*31-01-2024*

Mary Beard's manifesto—a brief, historically backed overview on the role of society and culture on the matter of women's production of authoritative speech.

Beard uses examples from the classics, starting with the *Odyssey*'s opening where Telemachus sends Penelope away and tells her off for speaking action to some annoying musicians.

According to Beard, in the rare occasions women were allowed authoritative speech, the content was restricted to very specific themes.

- In defense of their honour, usually before committing suicide or accusing a man.
- To voice the interests of women as a whole.
- While acting in a stereotypically/archetypal male fashion, as a general/commander/ruler.

In this last case, most figures adopted male patterns of behaviour and speech, even acknowledging this in some cases—making themselves into men.

Very short, with a very simple point—even though the world has changed a lot since Beard's mother's time, there is still a cultural holdover that at the very least makes it more difficult for women to:

- Reach positions of power.
- Effect change using that power.

Beard focuses on prestigious leadership positions, using examples of well-known female politicians. It would have been a longer book, but I would have liked some thoughts on power in mundane settings. Of course, what she says applies to home life, normal non-leadership positions, etc., but it is left as an exercise for the reader and there might be interesting nuances in these other spheres. The book is effective but it hammers on a bit too much, although I believe that's the intention.

At the very end there is a bit on what to do. One suggestion she makes is to—paraphrasing—'think about power as an attribute or as a verb'. To power something. Easier for me to understand that in the statistics sense—you need a large enough sample to “power” an analysis—and it makes sense, anyways.

Should everyone read this book? Probably, it's so short. I imagine many (unfortunately men) would recoil at the title, just like I did. When that happened I almost stopped but I had a thought. Why does this book exist? Mary Beard is a world-class scholar; her field is ancient history, Rome mainly. Her issue is not feminism; her issue as a historian is humanism. She knows—and I think I do too—that most of what's written, about all issues, at all times, and by almost any author, is about and from the perspective of men. Any old non-fiction book that deals with a thing, like an event, a war, or even a concept (I guess that could also be war), is going to be about the human experience which, in literature, has been presented as male. Thinking this—that almost any other book I pick up is written with males at the center—made it not only easy but pushed me to continue reading.

10/10
